### ISSUE TITLE
TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by andreas-bulling** [waldur/python-freeipa#51]
Hi,

I've implemented my own little freeIPA management script to simplify frequent tasks (e.g. adding new users). I'm currently trying to extend it to also set `o_krbprincipalexpiration`, however, I receive an error message when trying to pass the DateTime object to `user_add`:

```
Traceback (most recent call last):
  File "/home/user/bin/ipa_manage.py", line 53, in <module>
    user = client.user_add(username, firstname, lastname, fullname, displayname, o_initials=initials, o_homedirectory=homedirectory, o_gecos=gecos, o_loginshell=loginshell, o_title=title, o_krbprincipalname=krbprincipalname, o_krbprincipalexpiration=krbprincipalexpiration, o_mail=email, o_userpassword=password)
  File "/home/user/.local/lib/python3.8/site-packages/python_freeipa/client_meta.py", line 25504, in user_add
    return self._request(method, _args, _params)
  File "/home/user/.local/lib/python3.8/site-packages/python_freeipa/client.py", line 323, in _request
    session_url, headers=headers, data=json.dumps(data), verify=self._verify_ssl
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

Code that fills `krbprincipalexpiration`:

```
from datetime import date
from datetime import datetime
[...]
expiry = input("Account expiry date (YYYY-MM-DD): ")
krbprincipalexpiration = datetime.combine(datetime.fromisoformat(expiry), datetime.min.time())
```

Does anyone have a tip for how to make this work? Or is this a bug given that the official documentation suggests that DateTime is the correct type?

**Comment by AmbientLighter** [comment]
Yes, docs are not correct. Please try to serialize date `krbprincipalexpiration = krbprincipalexpiration.isoformat()`

**Comment by andreas-bulling** [comment]
```
Traceback (most recent call last):
  File "/home/user/bin/ipa_manage.py", line 54, in <module>
    user = client.user_add(username, firstname, lastname, fullname, displayname, o_initials=initials, o_homedirectory=homedirectory, o_gecos=gecos, o_loginshell=loginshell, o_title=title, o_krbprincipalname=krbprincipalname, o_krbprincipalexpiration=krbprincipalexpiration, o_mail=email, o_userpassword=password)
  File "/home/user/.local/lib/python3.8/site-packages/python_freeipa/client_meta.py", line 25504, in user_add
    return self._request(method, _args, _params)
  File "/home/user/.local/lib/python3.8/site-packages/python_freeipa/client.py", line 335, in _request
    parse_error(error)
  File "/home/user/.local/lib/python3.8/site-packages/python_freeipa/exceptions.py", line 117, in parse_error
    raise exception_class(message, code)
python_freeipa.exceptions.BadRequest: invalid 'principal_expiration': does not match any of accepted formats: %Y%m%d%H%M%SZ, %Y-%m-%dT%H:%M:%SZ, %Y-%m-%dT%H:%MZ, %Y-%m-%dZ, %Y-%m-%d %H:%M:%SZ, %Y-%m-%d %H:%MZ
```

**Comment by AmbientLighter** [comment]
Okay, let's try `krbprincipalexpiration = krbprincipalexpiration.strftime('%Y-%m-%dT%H:%MZ')` instead.

**Comment by andreas-bulling** [comment]
worked, thanks a lot!
